name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./.examples/dockerfiles/full/apache
        file: ./.examples/dockerfiles/full/apache
        platforms: linux/amd64, linux/arm64
        push: true
        tags: vanile/nextcloud-full:latest, vanile/nextcloud-full:$(date +'%Y-%m-%d')

